### ISSUE TITLE
ADT messages with UB2 fail from datica template

### ISSUE THREAD

**Issue by mwiley63** [daticahealth/Mirth-Transforms#6]
I noticed this when testing ADT messages with a UB2 segment, however this issue is related to any segments that are parsed in the ADT template using `hl7Json`, where it should be `hl7JSON` (note the capitalization difference).

**Comment by mwiley63** [comment]
I've attached an updated version of this template that works with all ADT segments.

[hl7_v2.3_ADT_to_JSON.xml.zip](https://github.com/daticahealth/Mirth-Transforms/files/2112588/hl7_v2.3_ADT_to_JSON.xml.zip)

**Comment by rwattras9** [comment]
Thanks for reporting this Matt! I've just pushed an update through with a fix for some of the typos that caused that issue, among some other minor fixes as well.
Let us know if you see any further issues!
